# NOTES: This is the baseline model
#        MR model trained with volume loss on lv interior
data:
    train_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/train/mr/augment20/processed
    validation_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/validation/mr/processed
    template_filename: data/template/highres_template.vtp
    point_cloud_filename: data/template/lv_interior_torch.pkl
    output_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/trained_models/mr/flow/model-4
train:
    num_epochs: 50
    batch_size: 1
    optimizer:
        lr: 1.e-4
        weight_decay: 1.e-4
    scheduler:
        factor: 0.9
        patience: 5
        threshold: 1.e-4
        min_lr: 1.e-6
model:
    pretrained_encoder: /global/scratch/users/arjunnarayanan/WholeHeartData/trained_models/mr/flow/pretrained_encoder.pth
    pretrained_linear_transform: /global/scratch/users/arjunnarayanan/WholeHeartData/trained_models/mr/flow/pretrained_linear_transform.pth
    encoder:
        input_shape: 128
        input_channels: 65
        first_layer_channels: 32
        downarm_channels: [32, 32, 64, 128, 256]
        uparm_channels: [256, 128, 64, 32, 32]
    flow:
        decoder_hidden_channels: 32
        clip: 0.05
    segment:
        decoder_hidden_channels: 32
        output_channels: 8
    integrator:
        num_steps: 20
loss:
    norm_type: 1
    chamfer_distance: 2
    chamfer_normal: 0.05
    divergence: 0.01
    edge: 50
    normal: 1
    laplace: 10
    cross_entropy: 0
    dice: 0