data:
    train_folder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/train
    validation_folder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/validation
    template_filename: data/template/highres_template.vtp
    outpud_folder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/trained_models/linear_transform/direct_linear_transform
train:
    num_epochs: 50
    batch_size: 2
    optimizer:
        lr: 1.e-4
        weight_decay: 1.e-5
    scheduler:
        factor: 0.9
        patience: 5
        threshold: 1.e-4
        min_lr: 1.e-6
model:
    input_shape: 128
    input_channels: 1
    first_layer_channels: 64
    downarm_channels: [64, 128, 256, 512, 1024]
loss:
    norm_type: 1