files:
  model: /global/scratch/users/arjunnarayanan/WholeHeartData/trained_models/segment_flow/pretrained_direct_linear_transform.pth
  out_dir: /global/scratch/users/arjunnarayanan/WholeHeartData/trained_models/linear_transform/evaluation/ct
  template: data/template/highres_template.vtp
  root_dir: /global/scratch/users/arjunnarayanan/WholeHeartData/indexed_raw_validation/ct
modality: ct