info:
  input_size: [128, 128, 128]
  num_mesh: 7
files:
  extension: .nii.gz
  model: /global/scratch/users/arjunnarayanan/WholeHeartData/trained_models/mr/flow/model-1/best_model.pth
  template: data/template/highres_template.vtp
  root_dir: /global/scratch/users/arjunnarayanan/MMWHS_test/mr_test
  output_dir: /global/scratch/users/arjunnarayanan/WholeHeartData/trained_models/mr/flow/model-1/evaluation/test/mr
  output_extension: .nii.gz
modality: mr