# NOTES: Baseline model
#       Trained on combined CT and cropped MR data
data:
    train_folder: /global/scratch/users/arjunnarayanan/WholeHeart-ct-crop-mr/train/
    validation_folder: /global/scratch/users/arjunnarayanan/WholeHeart-ct-crop-mr/validation
    template_filename: data/template/highres_template.vtp
    output_folder: /global/scratch/users/arjunnarayanan/WholeHeart-ct-crop-mr/trained_models/flow/model-1
train:
    num_epochs: 50
    batch_size: 1
    optimizer:
        lr: 5.e-5
        weight_decay: 5.e-5
    scheduler:
        factor: 0.9
        patience: 5
        threshold: 1.e-4
        min_lr: 1.e-6
model:
    pretrained_encoder: /global/scratch/users/arjunnarayanan/WholeHeart-ct-crop-mr/trained_models/flow/pretrained_encoder.pth
    pretrained_linear_transform: /global/scratch/users/arjunnarayanan/WholeHeart-ct-crop-mr/trained_models/flow/pretrained_linear_transform.pth
    encoder:
        input_shape: 128
        input_channels: 65
        first_layer_channels: 32
        downarm_channels: [32, 32, 64, 128, 256]
        uparm_channels: [256, 128, 64, 32, 32]
    flow:
        decoder_hidden_channels: 32
        clip: 0.05
    segment:
        decoder_hidden_channels: 32
        output_channels: 8
    integrator:
        num_steps: 10
loss:
    norm_type: 1
    chamfer_distance: 1
    chamfer_normal: 0.05
    divergence: 0.005
    edge: 20
    normal: 10
    laplace: 10
    cross_entropy: 0.05
    dice: 0.05