info:
  input_size: [128, 128, 128]
  num_mesh: 7
files:
  extension: .mha
  model: model/best_model.pth
  template: data/template/whole_heart_with_ao.vtp
  root_dir: data_coro
  output_dir: output/predict/data_coro
  output_extension: .nii.gz
modality: ct
