info:
  input_size: [128, 128, 128]
  num_mesh: 7
files:
  extension: .nii.gz
  model: output/WholeHeartData/trained_models/cropped/mr/flow/model-1/best_model.pth
  template: data/template/highres_template.vtp
  root_dir: /Users/arjun/Documents/Research/SimCardio/Datasets/MMWHS_test/cropped-mr
  output_dir: output/WholeHeartData/trained_models/cropped/mr/flow/model-1/evaluation/test/
  output_extension: .nii.gz
modality: mr