info:
  input_size: [128, 128, 128]
files:
  model: output/flow/chn-5/best_model_dict.pth
  out_dir: output/flow/chn-5/evaluation/ct
  template: data/template/highres_template.vtp
  root_dir: /Users/arjun/Documents/Research/SimCardio/Datasets/HeartData/raw_validation/ct
modality: ct