files:
  model: output/segment_flow/model-3/best_model_dict.pth
  out_dir: output/segment_flow/model-3/evaluation/ct
  template: data/template/highres_template.vtp
  root_dir: /Users/arjun/Documents/Research/SimCardio/Datasets/HeartDataSegmentation/raw_validation/ct
modality: ct