input_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/combined/mr-cropped-augment-0/processed
output_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/combined/mr-cropped-augment-0/processed/data
seg_labels: [0, 205, 420, 500, 550, 600, 820, 850]