input_folder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/validation/
output_folder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/validation/data
seg_labels: [0, 205, 420, 500, 550, 600, 820, 850]