input_folder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/train_no_augmentation/
output_folder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/train_no_augmentation/data
seg_labels: [0, 205, 420, 500, 550, 600, 820, 850]