input_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/cropped/mr/validation/processed
output_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/cropped/mr/validation/processed/data
seg_labels: [0, 205, 420, 500, 550, 600, 820, 850]