input_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/train/combined
output_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/train/combined/data
seg_labels: [0, 205, 420, 500, 550, 600, 820, 850]