checkpoint: output/flow/chn-5/best_model_dict.pth
output_dir: output/flow/chn-5/predictions/meshes
template: data/template/highres_template.vtp
dataset: /Users/arjun/Documents/Research/SimCardio/Datasets/HeartDataSegmentation/indexed_validation