output_dir: output/linear_transform_mcnn_5/predictions/meshes
checkpoint: output/linear_transform_mcnn_5/best_model_dict.pth
template: data/template/highres_template.vtp
dataset: /Users/arjun/Documents/Research/SimCardio/Datasets/HeartDataSegmentation/validation