info:
  input_size: [128, 128, 128]
  num_mesh: 7
files:
  extension: .nii.gz
  model: output/segment_flow/model-3/best_model_dict.pth
  template: data/template/highres_template.vtp
  root_dir: /global/scratch/users/arjunnarayanan/MMWHS_test/ct_test1
  output_dir: output/HeartData/flow/L1-64-baseline/evaluation/MMWHS_test/ct_test2
  output_extension: .nii.gz
modality: ct