checkpoint: output/segment_flow/model-2/best_model_dict.pth
output_dir: output/segment_flow/model-2/predictions/meshes
template: data/template/highres_template.vtp
dataset: /Users/arjun/Documents/Research/SimCardio/Datasets/HeartDataSegmentation/indexed_validation