checkpoint: output/segment_flow/model-3/best_model_dict.pth
output_dir: output/segment_flow/model-3/predictions/segmentation
template: data/template/highres_template.vtp
input_dir: /Users/arjun/Documents/Research/SimCardio/Datasets/HeartDataSegmentation/indexed_validation