info:
  input_size: [128, 128, 128] # input image dimensions
  num_mesh: 7 # number of mesh components
files:
  extension: .nii.gz # input image file extension
  model: /path/to/trained/model
  template: data/template/highres_template.vtp
  template_distance_map: data/template/highres_template_distance.vtk
  root_dir: /path/to/base/directory/of/input/images
  output_dir: /path/to/output/folder
  output_extension: .nii.gz
modality: ct # change to mr for MRI modality