info:
  input_size: [128, 128, 128]
  num_mesh: 7
files:
  extension: .nii.gz
  model: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/trained_models/segment_flow/model-5/best_model.pth
  template: data/template/highres_template.vtp
  root_dir: /global/scratch/users/arjunnarayanan/MMWHS_test/mr
  output_dir: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/trained_models/segment_flow/model-5/test/mr
  output_extension: .nii.gz
modality: mr