# NOTES: Based on model-3
# differences: extra layer in u-net. Unified decoder architecture. Higher weight on divergence loss
data:
    train_folder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/train
    validation_folder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/validation
    template_filename: data/template/highres_template.vtp
    output_folder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/trained_models/segment_flow/unified-1
train:
    num_epochs: 50
    batch_size: 1
    optimizer:
        lr: 5.e-5
        weight_decay: 5.e-5
    scheduler:
        factor: 0.9
        patience: 5
        threshold: 1.e-4
        min_lr: 1.e-6
model:
    pretrained_encoder: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/trained_models/segment_flow/pretrained_encoder.pth
    pretrained_linear_transform: /global/scratch/users/arjunnarayanan/HeartDataSegmentation/trained_models/segment_flow/pretrained_linear_transform.pth
    encoder:
        input_shape: 128
        input_channels: 66
        first_layer_channels: 32
        downarm_channels: [32, 32, 64, 128, 256, 256]
        uparm_channels: [256, 256, 128, 64, 32, 32]
    decoder:
        hidden_channels: 32
        output_channels: 11
    integrator:
        num_steps: 50
    clip_flow: -1
loss:
    norm_type: 1
    chamfer_distance: 1
    chamfer_normal: 0.5
    divergence: 0.05
    edge: 50
    normal: 5
    laplace: 10
    cross_entropy: 0.2
    dice: 1