# Based on model-1
# Changes: 
#   increase edge, normal, laplace to avoid mesh distortions
data:
    train_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/train/combined
    validation_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/validation/combined
    template_filename: data/template/highres_template.vtp
    output_folder: /global/scratch/users/arjunnarayanan/WholeHeartData/trained_models/cropped_segment_flow/model-2
train:
    num_epochs: 50
    batch_size: 1
    optimizer:
        lr: 5.e-5
        weight_decay: 1.e-4
    scheduler:
        factor: 0.9
        patience: 5
        threshold: 1.e-4
        min_lr: 1.e-6
    eval_frequency: 0.1
model:
    pretrained_linear_transform: /global/scratch/users/arjunnarayanan/WholeHeartData/trained_models/cropped_segment_flow/pretrained_direct_linear_transform.pth
    encoder:
        input_shape: 128
        input_channels: 2
        first_layer_channels: 32
        downarm_channels: [32, 32, 64, 128, 256, 256]
        uparm_channels: [256, 256, 128, 64, 64, 32]
    flow:
        hidden_channels: 32
        clip: 0.05
    segment:
        hidden_channels: 32
        output_channels: 8
    integrator:
        num_steps: 50
loss:
    norm_type: 1
    chamfer_distance: 1
    chamfer_normal: 0.1
    divergence: 0
    edge: 100
    normal: 10
    laplace: 20
    cross_entropy: 0.5
    dice: 0.5